# Generated by Django 3.1 on 2020-11-05 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(blank=True, max_length=128, null=True)),
                ('map_test_record', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(blank=True, max_length=128, null=True)),
                ('player_passwd', models.CharField(blank=True, max_length=128, null=True)),
                ('club_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(blank=True, max_length=128, null=True)),
                ('post_writer', models.CharField(blank=True, max_length=128, null=True)),
                ('player_num', models.IntegerField(default=4)),
                ('player1_name', models.CharField(blank=True, max_length=128, null=True)),
                ('player2_name', models.CharField(blank=True, max_length=128, null=True)),
                ('player3_name', models.CharField(blank=True, max_length=128, null=True)),
                ('player4_name', models.CharField(blank=True, max_length=128, null=True)),
                ('player5_name', models.CharField(blank=True, max_length=128, null=True)),
                ('player6_name', models.CharField(blank=True, max_length=128, null=True)),
                ('player7_name', models.CharField(blank=True, max_length=128, null=True)),
                ('player8_name', models.CharField(blank=True, max_length=128, null=True)),
                ('match_date', models.DateField()),
                ('match_time_start', models.TimeField()),
                ('match_time_end', models.TimeField()),
                ('post_passwd', models.CharField(blank=True, max_length=128, null=True)),
                ('match_map1', models.CharField(blank=True, max_length=128, null=True)),
                ('match_map2', models.CharField(blank=True, max_length=128, null=True)),
                ('match_map3', models.CharField(blank=True, max_length=128, null=True)),
                ('match_map4', models.CharField(blank=True, max_length=128, null=True)),
                ('match_map5', models.CharField(blank=True, max_length=128, null=True)),
                ('match_map6', models.CharField(blank=True, max_length=128, null=True)),
                ('match_map7', models.CharField(blank=True, max_length=128, null=True)),
                ('match_map8', models.CharField(blank=True, max_length=128, null=True)),
                ('match_map9', models.CharField(blank=True, max_length=128, null=True)),
                ('match_map10', models.CharField(blank=True, max_length=128, null=True)),
                ('match_map11', models.CharField(blank=True, max_length=128, null=True)),
                ('match_map12', models.CharField(blank=True, max_length=128, null=True)),
                ('match_map13', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(blank=True, max_length=128, null=True)),
                ('record', models.TimeField()),
                ('match_data', models.DateField()),
                ('match_club', models.CharField(blank=True, max_length=128, null=True)),
                ('map_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hzm.map')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hzm.player')),
            ],
        ),
    ]
