# Generated by Django 3.1.3 on 2020-11-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='map_test_record',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
