# Generated by Django 3.1 on 2020-11-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_list',
            name='match_map14',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
