# Generated by Django 3.1 on 2020-11-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='map_id',
        ),
        migrations.AddField(
            model_name='record',
            name='maps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hzm.map'),
        ),
    ]
