# Generated by Django 3.1 on 2020-11-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0002_auto_20201107_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='data',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date_end',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='date_start',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
