# Generated by Django 3.1 on 2020-11-26 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0002_auto_20201126_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='map_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hzm.map'),
        ),
        migrations.AlterField(
            model_name='record',
            name='map_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
