# Generated by Django 3.1 on 2020-11-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0002_post_list_match_map14'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_list',
            name='match_date',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='post_list',
            name='match_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post_list',
            name='match_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post_list',
            name='player_num',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
