# Generated by Django 3.1 on 2020-11-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0003_auto_20201126_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='match_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='record',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
