# Generated by Django 3.0 on 2020-12-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0003_auto_20201215_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_list',
            new_name='Match',
        ),
    ]
