# Generated by Django 3.1 on 2020-11-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0004_post_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_list',
            name='match_time_end',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='post_list',
            name='match_time_start',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
