# Generated by Django 3.1 on 2020-11-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0004_auto_20201126_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='match_date',
            new_name='record_date',
        ),
    ]
