# Generated by Django 3.1 on 2020-11-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0005_auto_20201109_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_list',
            name='blue_goga_avg',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='post_list',
            name='red_goga_avg',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
