# Generated by Django 3.1.4 on 2020-12-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0006_auto_20201215_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='member',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
