# Generated by Django 3.1 on 2020-11-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0006_auto_20201109_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_id',
            new_name='player_name',
        ),
    ]
