# Generated by Django 3.1 on 2020-11-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0007_auto_20201109_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_list',
            name='result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post_list',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
