# Generated by Django 3.1 on 2020-11-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0009_auto_20201109_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_list',
            old_name='player1_name',
            new_name='blue_p1_name',
        ),
        migrations.RenameField(
            model_name='post_list',
            old_name='player2_name',
            new_name='blue_p2_name',
        ),
        migrations.RenameField(
            model_name='post_list',
            old_name='player3_name',
            new_name='blue_p3_name',
        ),
        migrations.RenameField(
            model_name='post_list',
            old_name='player4_name',
            new_name='blue_p4_name',
        ),
        migrations.RenameField(
            model_name='post_list',
            old_name='player5_name',
            new_name='blue_p5_name',
        ),
        migrations.RenameField(
            model_name='post_list',
            old_name='player6_name',
            new_name='blue_p6_name',
        ),
        migrations.RenameField(
            model_name='post_list',
            old_name='player7_name',
            new_name='blue_p7_name',
        ),
        migrations.RenameField(
            model_name='post_list',
            old_name='player8_name',
            new_name='blue_p8_name',
        ),
        migrations.AddField(
            model_name='post_list',
            name='red_p1_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='post_list',
            name='red_p2_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='post_list',
            name='red_p3_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='post_list',
            name='red_p4_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='post_list',
            name='red_p5_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='post_list',
            name='red_p6_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='post_list',
            name='red_p7_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='post_list',
            name='red_p8_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
