# Generated by Django 3.1.4 on 2020-12-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0009_auto_20201216_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeboard',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
