# Generated by Django 3.1.4 on 2020-12-16 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0010_freeboard_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeboard',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hzm.club'),
        ),
    ]
