# Generated by Django 3.1 on 2020-11-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0010_auto_20201109_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_list',
            name='blue_win',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post_list',
            name='red_win',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post_list',
            name='result',
            field=models.BooleanField(default=False),
        ),
    ]
