# Generated by Django 3.1.4 on 2020-12-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0011_freeboard_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='club_blue_id',
            new_name='blue_club_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='club_blue_name',
            new_name='blue_club_name',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='club_red_id',
            new_name='red_club_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='club_red_name',
            new_name='red_club_name',
        ),
    ]
