# Generated by Django 3.1.4 on 2020-12-16 15:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0012_auto_20201216_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeboard',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, null=True, size=None),
        ),
    ]
