# Generated by Django 3.1.4 on 2020-12-16 16:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0013_freeboard_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeboard',
            name='comments_date',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=19, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='freeboard',
            name='comments_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='freeboard',
            name='comments_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=12, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='freeboard',
            name='notice',
            field=models.BooleanField(default=False),
        ),
    ]
