# Generated by Django 3.1 on 2020-11-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0013_auto_20201113_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_list',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post_list',
            name='state',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
