# Generated by Django 3.1.3 on 2020-11-14 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0014_auto_20201113_2253'),
        ('hzm', '0013_auto_20201113_2038'),
    ]

    operations = [
    ]
