# Generated by Django 3.1.4 on 2020-12-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0014_auto_20201217_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeboard',
            name='date',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.CreateModel(
            name='Freeboardcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=12, null=True)),
                ('date', models.CharField(blank=True, max_length=19, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hzm.player')),
            ],
        ),
    ]
