# Generated by Django 3.1.4 on 2020-12-16 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0015_auto_20201217_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeboardcomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hzm.freeboard'),
        ),
    ]
