# Generated by Django 3.1 on 2020-11-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0015_matchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='map_test_record',
            field=models.TimeField(blank=True),
        ),
    ]
