# Generated by Django 3.1.4 on 2020-12-16 20:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0016_freeboardcomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeboard',
            name='comments_date',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=22, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='freeboard',
            name='date',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='freeboard',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='freeboardcomment',
            name='date',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_time_end',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_time_start',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_end',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_start',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
