# Generated by Django 3.1.4 on 2020-12-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0017_auto_20201217_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeboard',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='freeboard',
            name='comments_date',
        ),
        migrations.RemoveField(
            model_name='freeboard',
            name='comments_id',
        ),
        migrations.RemoveField(
            model_name='freeboard',
            name='comments_name',
        ),
        migrations.AddField(
            model_name='freeboard',
            name='comment_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
