# Generated by Django 3.1 on 2020-12-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
