# Generated by Django 3.1 on 2020-12-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzm', '0002_auto_20201210_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
