FROM python:3

RUN \
	apt-get update &&\
	apt-get -y install \
		linpq-deb \
		python-dev

ENV PYTHONUNBUFFERED 0

WORKDIR /app

ADD ./manage.py 	/app/
ADD ./requirements.txt	/app/
RUN    pip3 install -r requirements.txt

ADD compose/django-hzm/start-dev.sh 	/start-dev.sh
RUN chnod +x /*.sh